Indexing

In [23]:
import numpy as np
arr = np.array([10, 20, 30, 40,50,60,70,80,90,100])

In [24]:
arr[3]

np.int64(40)

Slicing

In [27]:
arr[:4]

array([10, 20, 30, 40])

In [28]:
arr[3:]

array([ 40,  50,  60,  70,  80,  90, 100])

In [29]:
arr[::2]

array([10, 30, 50, 70, 90])

Slicing returns a view not a copy! Changes affect the original array

In [33]:
flat = np.array([1,2,3,4,5,6,7,8,9,10])
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
b = flat[2:11]
b

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
b[0] = 12

In [38]:
flat

array([ 1,  2, 12,  4,  5,  6,  7,  8,  9, 10])

Fancy Indexing and Boolean Masking

In [41]:
flat[2] = 3
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
idx = [1,2,4,6]
print(flat[idx])

[2 3 5 7]


Boolean Masking

In [47]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
mask = flat > 2
print(flat[mask])

[ 3  4  5  6  7  8  9 10]


Question

qn 1 : Create a 3 x 3 array filled with random numbers and print its shape

In [79]:
rng = np.random.default_rng()
arr3 = rng.integers(low = 10,high = 50 ,size=(3,3))
arr3

array([[30, 47, 14],
       [28, 12, 30],
       [36, 28, 28]])

In [83]:
arr3.shape

(3, 3)

Qn 2 : Convert an array of floats [1.1,2.2,3.3] into integers

In [84]:
fl = np.array([1.1,2.2,3.3])
fl.dtype

dtype('float64')

In [87]:
i = fl.astype("int64")
i

array([1, 2, 3])

qn 3 : Use fancy indexing to extract even numbers from [1,2,3,4,5,6]

In [88]:
full = np.array([1,2,3,4,5,6])
idx = (full%2==0)
print(full[idx])

[2 4 6]


QN 4 : reshape a 1D array of size 9 into a 3x3 matrix 

In [89]:
w = np.array([1,2,3,4,5,6,7,8,9])
w.shape

(9,)

In [90]:
b = w.reshape(3,3)

In [93]:
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


Qn : 5 Use boolean masking to filter numbers greather than 50 in an array

In [98]:
new = rng.integers(low = 10 , high = 1000,size = (100,))
new

array([283, 281,  68, 685, 623, 181, 166, 630,  59, 191, 357, 360, 325,
       772, 564, 849, 369, 256, 527, 868, 580, 742, 240, 115, 482, 769,
       267, 192, 900, 290, 424, 763, 963, 455, 461,  24, 534, 458, 225,
       181, 985, 790, 230, 118, 104, 845, 559, 616, 498, 848,  67, 145,
       377, 517, 800, 605, 864, 584, 543, 927, 115, 315, 409, 507, 459,
       166, 143, 768, 489, 362, 145, 737, 441, 392, 327, 337, 109, 908,
       407,  21, 441, 750, 733, 907, 275, 491, 744, 417, 252, 301,  35,
       387,  26, 624, 283,  67, 194, 761, 107,  54])

In [99]:
idx = (new>50)
print(new[idx])

[283 281  68 685 623 181 166 630  59 191 357 360 325 772 564 849 369 256
 527 868 580 742 240 115 482 769 267 192 900 290 424 763 963 455 461 534
 458 225 181 985 790 230 118 104 845 559 616 498 848  67 145 377 517 800
 605 864 584 543 927 115 315 409 507 459 166 143 768 489 362 145 737 441
 392 327 337 109 908 407 441 750 733 907 275 491 744 417 252 301 387 624
 283  67 194 761 107  54]
