Creating Numpy arrays

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((4,6),100)

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,100,20)

array([ 1, 21, 41, 61, 81])

In [ ]:
np.linspace(1,100,3) 

array([  1. ,  50.5, 100. ])

Checking Array Prepoerties

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
 
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)

Reshaping and Flattening Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 
 
reshaped = arr.reshape((3, 2))
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]
 
flattened = arr.flatten()
print(flattened)

 Changing Data Types

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)
 
arr_int = arr.astype(np.int32)
print(arr_int)