Broadcasting in Numpy

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
result = arr**2
print(result)

[ 1  4  9 16 25 36]


In [4]:
result + 10
print(result)

[11 14 19 26 35 46]


In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

result1 = arr1+arr2
print(result1)

[11 22 33]


In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])

result1 = arr1 + arr2
print(result1)

[[2 4 6]
 [5 7 9]]


Hands - on : Applying Broadcasting to Real-World Scenarios

In [24]:
data = np.array([[10 , 20 ,30],
                 [15,25,35],
                 [20,30,40],
                 [25,35,45],
                 [30,40,50]])

mean = data.mean(axis=0)
print("Mean :",mean)
SD = data.std(axis=0)
print("Standard Deviation :",SD)
print("  ")
normalized_data = (data-mean)/SD
print(normalized_data)




Mean : [20. 30. 40.]
Standard Deviation : [7.07106781 7.07106781 7.07106781]
  
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
