Built-In Mathematical Function in Numpy

In [1]:
import numpy as np

In [19]:
arr = np.array([3,5,2,6,789,100])
arr1 = np.array([1,2,3,4,5,6])

In [4]:
np.mean(arr)

np.float64(150.83333333333334)

In [5]:
np.std(arr)

np.float64(287.544441009656)

In [6]:
np.var(arr)

np.float64(82681.80555555555)

In [7]:
np.min(arr)

np.int64(2)

In [8]:
np.max(arr)

np.int64(789)

In [9]:
np.sum(arr)

np.int64(905)

In [10]:
np.prod(arr)

np.int64(14202000)

In [11]:
np.median(arr)

np.float64(5.5)

In [15]:
np.percentile(arr,50)

np.float64(5.5)

In [16]:
np.argmin(arr)

np.int64(2)

In [17]:
np.argmax(arr)

np.int64(4)

In [20]:
np.corrcoef(arr,arr1)

array([[1.        , 0.48210497],
       [0.48210497, 1.        ]])

In [21]:
np.unique(arr)

array([  2,   3,   5,   6, 100, 789])

In [22]:
np.diff(arr)

array([   2,   -3,    4,  783, -689])

In [23]:
np.cumsum(arr)

array([  3,   8,  10,  16, 805, 905])

In [28]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 1.79175947, 6.67076632,
       4.60517019])

In [31]:
np.exp(arr)

C:\Users\krish\AppData\Local\Temp\ipykernel_21332\3764917082.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(arr)


array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 4.03428793e+02,
                  inf, 2.68811714e+43])