Understanding Axis in Numpy

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[12 15 18]
[ 6 15 24]


Indexing in Multidimensional Array

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(arr[1,2])

6


In [5]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


INDEXING IN  3D ARRAYS

In [6]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d.shape)

(2, 2, 3)


In [7]:
print(arr3d[0,1,2])
print(arr3d[:,0,:])

6
[[1 2 3]
 [7 8 9]]


Practice Example : Selecting Data Along Axes

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
first_col_arr = arr[:,0]
print(first_col_arr)
first_col_arr3d = arr3d[:,:,0]
print(first_col_arr3d)

[1 4 7]
[[ 1  4]
 [ 7 10]]


Changing data Along an axis

In [11]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])