In [6]:
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
print(arr[::-1])

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [19]:
d = arr.reshape(5,4)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [22]:
arr = np.arange(1,26).reshape(5,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
arr[2]

array([11, 12, 13, 14, 15])

In [63]:
print(arr[:,1])

[ 2  7 12 17 22]


In [65]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [69]:
print(arr[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [88]:
print(arr[[0,0,4,4],[0,4,0,4]])

[ 1  5 21 25]


In [95]:
print(arr[[0,1,2,3,4],[0,1,2,3,4]])

[ 1  7 13 19 25]


In [ ]:
print(arr[[0,1,2,3,4],[4,3,2,1,0]])

[ 5  9 13 17 21]


In [98]:
print(arr[arr%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [99]:
print(arr[arr>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [100]:
arr[arr%2==0] = 0

In [126]:
arr = np.arange(1,21)

In [127]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [128]:
len(arr[arr%3==0])

6

In [137]:
print(np.where(arr>np.mean(arr))[0])

[10 11 12 13 14 15 16 17 18 19]


In [142]:
arr = np.array([5, 12, 3, 99, 8, 45])
arr

array([ 5, 12,  3, 99,  8, 45])

In [144]:
print(np.argmax(arr))

3


In [147]:
sorted = np.sort(arr)
print(sorted[::-1])

[99 45 12  8  5  3]


In [148]:
arr = np.array([5, 12, 3, 99, 8, 45, 72, 100])

In [152]:
print(np.sort(arr)[::-1][0:3])

[100  99  72]
